MvcSeleniumScraper/MvcSeleniumScraper/Models/Stock.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSeleniumScraper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string Symbol { get; set; }
        public double LastPrice { get; set; }
        public double ChangePercent { get; set; }
        public string Volume { get; set; }
        public string AvgVol { get; set; }
        public string MarketCap { get; set; }
    }
}

MvcSeleniumScraper/MvcSeleniumScraper/Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcSeleniumScraper.Models;
using MvcSeleniumScraper.ScraperService;

namespace MvcSeleniumScraper.Controllers
{
    [OverrideAuthorization]
    [Authorize]
    public class StocksController : Controller
    {
        private StockDataEntities5 db = new StockDataEntities5();

        // GET: Stocks
     //   [Authorize]
        public ActionResult Index()
        {
            return View(db.Stocks.ToList());
        }

      //  [Authorize]
        public ActionResult NewScrape()
        {
            if (ModelState.IsValid)
            {
                var scrape = new Scrape("webdriverproj", "Monkeys123");

                scrape.LogIn();
                scrape.NavigateToYahooFinance();
                scrape.ScrapeStockData();
            }
            return Redirect("Index");
        }

        // GET: Stocks/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Stock stock = db.Stocks.Find(id);
            if (stock == null)
            {
                return HttpNotFound();
            }
            return View(stock);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcSeleniumScraper/MvcSeleniumScraper/Views/Stocks/Details.cshtml
@model MvcSeleniumScraper.Models.Stock

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Stock</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Change)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Change)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChangePercent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChangePercent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Volume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Volume)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvgVol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvgVol)
        </dd>

        <dt> 
            @Html.DisplayNameFor(model => model.MarketCap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarketCap)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

MvcSeleniumScraper/MvcSeleniumScraper/Views/Stocks/Index.cshtml
@model IEnumerable<MvcSeleniumScraper.Models.Stock>

@{
    ViewBag.Title = "Index";
}

<h2 class="jumbotron">
    Yahoo Stocks
</h2>
<button>@Html.ActionLink("Update Stock Info", "NewScrape", "Stocks")</button>
<button>@Html.ActionLink("Stock History", "Index", "StockHistories")</button>


<table class="table table-hover display">
    <thead>
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Symbol)
            </th>
            <th class="text-center">
                Last Price
            </th>
            <th class="text-center">
                Change Percent
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Volume)
            </th>
            <th class="text-center">
                Average Volume
            </th>
            <th class="text-center">
                Market Cap
            </th>
        </tr>
    </thead>
    <tbody id="yahooCurrent" style="text-align: center">

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Symbol)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.LastPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ChangePercent)%
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Volume)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AvgVol)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.MarketCap)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Symbol })
                </td>
            </tr>
        }
    </tbody>
</table>