MvcSeleniumScraper/MvcSeleniumScraper/Models/WorldTradeStockHistory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSeleniumScraper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorldTradeStockHistory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Symbol { get; set; }
        public string Price { get; set; }
        public string Change { get; set; }
        public string ChangePercent { get; set; }
    }
}

MvcSeleniumScraper/MvcSeleniumScraper/Controllers/WorldTradeStockHistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcSeleniumScraper.Models;

namespace MvcSeleniumScraper.Controllers
{
    [Authorize]
    public class WorldTradeStockHistoriesController : Controller
    {
        private StockDataEntities4 db = new StockDataEntities4();

        // GET: WorldTradeStockHistories
        public ActionResult Index()
        {
            return View(db.WorldTradeStockHistories.ToList());
        }

        [Authorize]
        public ActionResult ClearStockHistory()
        {
            if (ModelState.IsValid)
            {
                RestSharpScraperService.Database.Clear_Reset();
            }

            return Redirect("/WorldTradeStockCurrents");
        }

        // GET: WorldTradeStockHistories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorldTradeStockHistory worldTradeStockHistory = db.WorldTradeStockHistories.Find(id);
            if (worldTradeStockHistory == null)
            {
                return HttpNotFound();
            }
            return View(worldTradeStockHistory);
        }

        // GET: WorldTradeStockHistories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WorldTradeStockHistories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Symbol,Price,Change,ChangePercent")] WorldTradeStockHistory worldTradeStockHistory)
        {
            if (ModelState.IsValid)
            {
                db.WorldTradeStockHistories.Add(worldTradeStockHistory);
                db.SaveChanges();
            }
            return RedirectToAction("Index");


           // return View(worldTradeStockHistory);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcSeleniumScraper/MvcSeleniumScraper/Views/WorldTradeStockHistories/Create.cshtml
@model MvcSeleniumScraper.Models.WorldTradeStockHistory

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WorldTradeStockHistory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Symbol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Symbol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Symbol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Change, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Change, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Change, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChangePercent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChangePercent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChangePercent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcSeleniumScraper/MvcSeleniumScraper/Views/WorldTradeStockHistories/Details.cshtml
@model MvcSeleniumScraper.Models.WorldTradeStockHistory

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>WorldTradeStockHistory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Symbol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Symbol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Change)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Change)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChangePercent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChangePercent)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcSeleniumScraper/MvcSeleniumScraper/Views/WorldTradeStockHistories/Index.cshtml
@model IEnumerable<MvcSeleniumScraper.Models.WorldTradeStockHistory>

@{
    ViewBag.Title = "Index";
}

<script src="//code.jquery.com/jquery.min.js"></script>
<script src="~/Scripts/paginathing.js"></script>

<h2 class="jumbotron">WorldTradeData API Stock History</h2>

<p>
    <button>@Html.ActionLink("Current", "Index", "WorldTradeStockCurrents")</button>
</p>
<table id="pagnation" class="table table-hover">
    <thead>
        <tr >
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Symbol)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Change)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.ChangePercent)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="worldTrade">
        @foreach (var item in Model)
        {
            <tr class="text-center">
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Symbol)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Change)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ChangePercent)%
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <button>@Html.ActionLink("Clear Stock History", "ClearStockHistory", "WorldTradeStockHistories")</button>
</div>

<script>
    $('#worldTrade').paginathing({
        perPage: 5,
    });

</script>