IronScraperMVC/IronScraperMVC/Models/FinancialContentCurrent.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronScraperMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialContentCurrent
    {
        public string Name { get; set; }
        public string Symbol { get; set; }
        public string Price { get; set; }
        public string PriceChange { get; set; }
        public string ChangePercent { get; set; }
        public string Volume { get; set; }
    }
}

IronScraperMVC/IronScraperMVC/Models/FinancialContentHistory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronScraperMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialContentHistory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Symbol { get; set; }
        public string Price { get; set; }
        public string PriceChange { get; set; }
        public string ChangePercent { get; set; }
        public string Volume { get; set; }
    }
}

IronScraperMVC/IronScraperMVC/Models/IronStocks.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronScraperMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockDataEntities : DbContext
    {
        public StockDataEntities()
            : base("name=StockDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FinancialContentCurrent> FinancialContentCurrents { get; set; }
        public virtual DbSet<FinancialContentHistory> FinancialContentHistories { get; set; }
    }
}

IronScraperMVC/IronScraperMVC/Models/IronStocks.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Owner\source\repos\WebScraper\IronScraperMVC\IronScraperMVC\Models\IronStocks.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

IronScraperMVC/IronScraperMVC/Models/IronStocks.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

IronScraperMVC/IronScraperMVC/Controllers/FinancialContentCurrentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IronScraperMVC.Models;
using IronScraperMVC.ScraperService;

namespace IronScraperMVC.Controllers
{
    public class FinancialContentCurrentsController : Controller
    {
        private StockDataEntities db = new StockDataEntities();

        // GET: FinancialContentCurrents
        public ActionResult Index()
        {
            return View(db.FinancialContentCurrents.ToList());
        }

        public ActionResult NewScrape()
        {
            if (ModelState.IsValid)
            {
                var scraper = new Scraper();
                scraper.Start();
                scraper.AddStockToDatabase();
            }
            return Redirect("Index");
        }

        // GET: FinancialContentCurrents/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FinancialContentCurrent financialContentCurrent = db.FinancialContentCurrents.Find(id);
            if (financialContentCurrent == null)
            {
                return HttpNotFound();
            }
            return View(financialContentCurrent);
        }
    }
}

IronScraperMVC/IronScraperMVC/Controllers/FinancialContentHistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IronScraperMVC.Models;

namespace IronScraperMVC.Controllers
{
    public class FinancialContentHistoriesController : Controller
    {
        private StockDataEntities db = new StockDataEntities();

        // GET: FinancialContentHistories
        public ActionResult Index()
        {
            return View(db.FinancialContentHistories.ToList());
        }

        [Authorize]
        public ActionResult ClearStockHistory()
        {
            if (ModelState.IsValid)
            {
                ScraperService.Database.Clear_Reset();
            }
            return Redirect("/FinancialContentCurrents");
        }


        // GET: FinancialContentHistories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FinancialContentHistory financialContentHistory = db.FinancialContentHistories.Find(id);
            if (financialContentHistory == null)
            {
                return HttpNotFound();
            }
            return View(financialContentHistory);
        }

    
    }
}

IronScraperMVC/IronScraperMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IronScraperMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

IronScraperMVC/IronScraperMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Stocks</h1>
</div>

<div class="container">
    <button id="test">@Html.ActionLink("Current Data", "Index", "FinancialContentCurrents", null, new { @class = "my-class" })</button>
    <button>@Html.ActionLink("Stock History", "Index", "FinancialContentHistories")</button>
</div>

IronScraperMVC/IronScraperMVC/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" id="styleNav" style="background-color:gainsboro;">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Stock Scraper</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>