MvcSeleniumScraper/MvcSeleniumScraper/Models/NasdaqStockHistory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSeleniumScraper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NasdaqStockHistory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Symbol { get; set; }
        public string Price { get; set; }
        public string Change { get; set; }
    }
}

MvcSeleniumScraper/MvcSeleniumScraper/Controllers/NasdaqStockHistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcSeleniumScraper.Models;

namespace MvcSeleniumScraper.Controllers
{
    public class NasdaqStockHistoriesController : Controller
    {
        private StockDataEntities1 db = new StockDataEntities1();

        // GET: NasdaqStockHistories
        public ActionResult Index()
        {
            return View(db.NasdaqStockHistories.ToList());
        }

        [Authorize]
        public ActionResult ClearStockHistory()
        {
            if (ModelState.IsValid)
            {
                HAPScraperService.Database.Clear_Reset();
            }
  
            return Redirect("/NasdaqStockCurrents");
        }
        // GET: NasdaqStockHistories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NasdaqStockHistory nasdaqStockHistory = db.NasdaqStockHistories.Find(id);
            if (nasdaqStockHistory == null)
            {
                return HttpNotFound();
            }
            return View(nasdaqStockHistory);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcSeleniumScraper/MvcSeleniumScraper/Views/NasdaqStockHistories/Details.cshtml
@model MvcSeleniumScraper.Models.NasdaqStockHistory

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>NasdaqStockHistory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Symbol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Symbol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Change)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Change)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcSeleniumScraper/MvcSeleniumScraper/Views/NasdaqStockHistories/Index.cshtml
@model IEnumerable<MvcSeleniumScraper.Models.NasdaqStockHistory>

@{
    ViewBag.Title = "Index";
}

<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/paginathing.js"></script>

<h2 class="jumbotron">
    Nasdaq's Most Active Stocks History
</h2>

<p>
    <button>@Html.ActionLink("Current Data", "Index", "NasdaqStockCurrents")</button>
</p>
<table id="pagnation" class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Symbol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Change)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="nasdaq">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Symbol)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Change)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <button>@Html.ActionLink("Clear Stock History", "ClearStockHistory", "NasdaqStockHistories")</button>
</div>

<script>
    $('#nasdaq').paginathing({
        perPage: 20,
    });
</script>